<% require "dotenv"; Dotenv.load(".env") %>

# Name of your application. Used to uniquely configure containers.
service: quran-detector-api

# Name of the container image.
image: ieasybooks/quran-detector-api

# Deploy to these servers.
servers:
  web:
    - <%= ENV["SERVER_IP"] %>
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: quran-detector-api.ieasybooks.com
  # Proxy connects to your container on port 80 by default.
  app_port: 8000

  healthcheck:
    path: /v1/healthz

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: ieasybooks

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  # Pass in additional build args needed for your Dockerfile.
  # args:
  #   RUBY_VERSION: <%= ENV["RBENV_VERSION"] || ENV["rvm_ruby_string"] || "#{RUBY_ENGINE}-#{RUBY_ENGINE_VERSION}" %>

  cache:
    type: gha
    options: mode=max
    image: quran-detector-api-build-cache

# Inject ENV variables into containers (secrets come from .kamal/secrets).
#
env:
  clear:
    QD_API_WORKERS: 2
  # secret:
  #   - RAILS_MASTER_KEY
